---
# tasks file for mysql
   - name: install tools
     apt: 
       pkg: 
       - python-mysqldb
       state: present
       update_cache: yes

   - name: install mysql
     apt: name=mysql-server state=present update_cache=yes

   - name: ensure mysql is listening on all ports
     lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address=0.0.0.0"
     notify: restart mysql

   - name: start service mysql
     service: name=mysql state=started enabled=yes

   - name: creater demo db
     mysql_db: name=demo state=present

   - name: create mysql user
     mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present 


