---
# tasks file for apache2
- name: install apache
  apt: 
    pkg:
    - apache2
    - libapache2-mod-wsgi
    state: present
  tags: [ 'packages']

- name: enable mod_wsgi
  apache2_module: name=wsgi state=present
  notify: restart apache2
  tags: [ 'config']

- name: deactivate default apache site 
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache
  tags: [ 'config']

- name: start service apache2
  service: name=apache2 state=started enabled=yes
  tags: [ 'service']
