---
 - hosts: database
   become: yes
   tasks:
   - name: install mysql
     apt: name=mysql-server state=present update_cache=yes

   - name: start service mysql
     service: name=mysql state=started enabled=yes
