---
 - hosts: loadbalancer
   become: yes
   tasks:
   - name: install nginx
     apt: name=nginx state=present update_cache=yes

   - name: start service nginx
     service: name=nginx state=started enabled=yes
