---
# Stop everything

 - hosts: loadbalancer
   become: true
   tasks:
   - service: name=nginx state=stopped
    
 - hosts: webserver
   become: true
   tasks:
   - service: name=apache2 state=stopped
    
 - hosts: database
   become: true
   tasks:
   - service: name=mysql state=restarted

# Start everything
    
 - hosts: webserver
   become: true
   tasks:
   - service: name=apache2 state=stopped
    
 - hosts: loadbalancer
   become: true
   tasks:
   - service: name=nginx state=started