---
 - hosts: webserver
   become: true
   tasks:
   - name: install apache
     apt: 
       pkg:
       - apache2
       - libapache2-mod-wsgi
       - python-pip
       - python-virtualenv
       state: present
       update_cache: yes


   - name: start service apache2
     service: name=apache2 state=started enabled=yes