---
 - hosts: webserver
   become: true
   tasks:
   - name: install apache
     apt: 
       pkg:
       - apache2
       - libapache2-mod-wsgi
       - python-pip
       - python-virtualenv
       state: present
       update_cache: yes


   - name: start service apache2
     service: name=apache2 state=started enabled=yes
     
   - name: enable mod_wsgi
     apache2_module: name=wsgi state=present
     notify: restart apache2
     
   - name: copy app source
     copy: src=/home/ansible/demo/app dest=/var/www/demo mode=0775
     notify: restart apache2
     
   - name: copy  virtual host config
     copy: src=/home/ansible/demo/demo.conf dest=/etc/apache2/sites-available mode=0775
     notify: restart apache2
     
   handlers:
   - name: restart apache2
     service: name=apache2 state=restarted