---
# tasks file for nginx
  - name: install tools
    apt:
      pkg:
      - python-httplib2
      state: present
    tags: [ 'packages']

  
  - name: install nginx
    apt: name=nginx state=present
    tags: [ 'packages']


  - name: configure nginx loadbalancer
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{item.key}} mode=0644
    with_dict: "{{ sites }}"
    notify: restart nginx
    tags: [ 'config']
   
  - name: get active sites
    shell: ls /etc/nginx/sites-enabled/
    register: active_sites
    changed_when: "active_sites.stdout_lines != sites.keys()"
    tags: [ 'config']

  - name: deactivate default nginx site 
    file: path=/etc/nginx/sites-enabled/{{item}} state=absent
    with_items: "{{active_sites.stdout_lines}}"
    when: item not in sites
    notify: restart nginx
    tags: [ 'config']

  - name: activate demo apache site 
    file: src=/etc/nginx/sites-available/{{item.key}} dest=/etc/nginx/sites-enabled/{{item.key}} state=link
    with_dict: "{{ sites }}"
    notify: restart nginx
    tags: [ 'config']

  - name: start service nginx
    service: name=nginx state=started enabled=yes
    tags: [ 'service']
